user  nginx;
worker_processes  auto;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # 这里的 upstream 名称要和 docker-compose.yml 里的服务名一致
    server {
        listen 3000;
        location / {
            proxy_pass http://grafana:3000;
        }
    }

    server {
        listen 9090;
        location / {
            proxy_pass http://prometheus:9090;
        }
    }

    server {
        listen 8080;
        location / {
            proxy_pass http://cadvisor:8080;
        }
    }

    server {
        listen 9093;
        location / {
            proxy_pass http://alertmanager:9093;
        }
    }
}